spring:
  profiles:
    include: default
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/postgres"
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
    username: root
    password: root
    url: "jdbc:postgresql://localhost:5432/postgres"
    driver-class-name: org.postgresql.Driver


jwtconfig:
  secret: secret
  expiration: 600