spring:
  profiles:
    include: default
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/RentCars"
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
      username: root
      password: root
    url: "jdbc:postgresql://localhost:5432/RentCars"
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    ignore-missing-migrations: true
    locations: classpath:/migration
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}


jwtconfig:
  secret: secret
  expiration: 6


server:
  port: 8080